// Generated by CoffeeScript 2.5.1
(function() {
  var assert, storeFfi;

  assert = require("assert");

  storeFfi = require("../../src/InMemoryStore");

  describe("All Tests", function() {
    return describe("set keys", function() {
      it("Should set keys", function() {
        return storeFfi._set("key")("val")();
      });
      it("Should get keys", function() {
        storeFfi._set("key")("val")();
        return assert.equal(storeFfi._get("key")(), "val");
      });
      return it("Should error release key values", function() {
        storeFfi._set("key")("val")();
        storeFfi.release("key")();
        return assert.equal(storeFfi._get("key")(), null);
      });
    });
  });

}).call(this);
