// Generated by CoffeeScript 2.5.1
(function() {
  var assert, exists, get, release, set, storeFfi;

  assert = require("assert");

  storeFfi = require("../../src/InMemoryStore");

  set = function(key, val) {
    return storeFfi._set(key)(val)();
  };

  get = function(key) {
    return storeFfi._get(key)();
  };

  exists = function(key) {
    return storeFfi.exists(key)();
  };

  release = function(key) {
    return storeFfi.release(key)();
  };

  describe("InMemoryStore FFI Tests", function() {
    // Clear the store before running each test
    beforeEach(function() {
      return storeFfi.flush();
    });
    it("Should release key values", function() {
      set("key", "val");
      release("key");
      return assert.equal(get("key"), null);
    });
    it("Should set keys", function() {
      return set("key", "val");
    });
    it("Should get keys", function() {
      set("key", "val");
      return assert.equal(get("key"), "val");
    });
    it("Should determine whether keys exist", function() {
      set("key", "val");
      assert.equal(exists("key"), true);
      return assert.equal(exists("foo"), false);
    });
    it("Should not return false positives when the store exists but not the key", function() {
      // Force the store to initialize
      set("key", "val");
      return assert.equal(exists("flim"), false);
    });
    return it("Should always return false for existence checks when the store is null", function() {
      return assert.equal(exists("flam"), false);
    });
  });

}).call(this);
