// Generated by CoffeeScript 2.5.1
(function() {
  var assert, exists, get, release, set, storeFfi;

  assert = require("assert");

  storeFfi = require("../../src/InMemoryStore");

  set = function(key, val) {
    return storeFfi._set(key)(val)();
  };

  get = function(key) {
    return storeFfi._get(key)();
  };

  exists = function(key) {
    return storeFfi.exists(key)();
  };

  release = function(key) {
    return storeFfi.release(key)();
  };

  describe("InMemoryStore FFI Tests", function() {
    // Clear the store before running each test
    beforeEach(function() {
      return storeFfi._set.store = null;
    });
    it("Should release key values", function() {
      set("key", "val");
      release("key");
      return assert.equal(get("key"), null);
    });
    it("Should set keys", function() {
      return set("key", "val");
    });
    it("Should get keys", function() {
      set("key", "val");
      return assert.equal(get("key"), "val");
    });
    return it("Should determine whether keys exist", function() {
      set("key", "val");
      assert.equal(exists("key"), true);
      return assert.equal(exists("foo"), false);
    });
  });

}).call(this);
